### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.kind
      - azure-servicefabric.TestErrorChaosEvent.reason
      - azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="9ad25-101">描述當混亂引擎就會發生未預期的事件時產生的混亂事件。</span><span class="sxs-lookup"><span data-stu-id="9ad25-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="9ad25-102">比方說，同時錯誤實體不一致，叢集中的快照集，因為混亂找到的實體已發生錯誤，就可能發生非預期的事件。</span><span class="sxs-lookup"><span data-stu-id="9ad25-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="9ad25-103">多型的鑑別子</span><span class="sxs-lookup"><span data-stu-id="9ad25-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="9ad25-104">描述為何產生 TestErrorChaosEvent。</span><span class="sxs-lookup"><span data-stu-id="9ad25-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="9ad25-105">比方說，混亂會嘗試容錯的資料分割，但會尋找資料分割不會再提供容錯功能，則產生 TestErrorEvent 原因指出分割區不具有容錯功能。</span><span class="sxs-lookup"><span data-stu-id="9ad25-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="9ad25-106">UTC 時間戳記時產生這個混亂事件。</span><span class="sxs-lookup"><span data-stu-id="9ad25-106">The UTC timestamp when this Chaos event was generated.</span></span>
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent